# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d1880f11794af87fff91df3a8dc82df96cb97fee53fa0010c5b53aa07e0831a532170cda57a1a6373ad8756de457aa615d90154a0381b53d4e92c4b7d2f66a6

test:
  secret_key_base: 321d8455b785df46864226757d725fca812c29597e26528abb55810644a1a6645a9ae160a3091417d6b507b3ba4f1793f5de4dd673195ca94f47bfea88cd1571

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
